### ISSUE TITLE
undefined method `node_attrs=

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/builderator#52]
It looks like there is a regression somewhere between [1.0.0-rc.10 and the tip of master](https://github.com/rapid7/builderator/compare/1.0.0-rc.10...f19074df2cb6d7dfd789bb1daf1d9323314e6e6d) related to `node_attrs`

A Buildfile snippit like this works in 1.0.0-rc.10, but throw the exception below on master.

``` ruby
profile :default do |default|
  default.chef do |chef|
    chef.node_attrs = { 'vagrant_userdata' => userdata }
  end
end
```

```
~/code/chef-rapid7-db7[master*]% be build config
/Users/athompson/code/chef-rapid7-db7/Buildfile:29:in `block (2 levels) in compile': undefined method `node_attrs=' for #<#<Class:0x007f8e23088618>:0x007f8e21a79fe8> (NoMethodError)
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:217:in `call'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:217:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `block in compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `each'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `block in compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `each'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `block in compile'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `each'
    from /Users/athompson/code/builderator/lib/builderator/config/attributes.rb:218:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/config/file.rb:51:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/config.rb:64:in `block (2 levels) in compile'
    from /Users/athompson/code/builderator/lib/builderator/config.rb:63:in `each'
    from /Users/athompson/code/builderator/lib/builderator/config.rb:63:in `block in compile'
    from /Users/athompson/code/builderator/lib/builderator/config.rb:58:in `loop'
    from /Users/athompson/code/builderator/lib/builderator/config.rb:58:in `compile'
    from /Users/athompson/code/builderator/lib/builderator/tasks.rb:29:in `initialize'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:355:in `new'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/athompson/code/builderator/bin/build:4:in `<top (required)>'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/build:23:in `load'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/build:23:in `<main>'
```

**Comment by athompson-r7** [comment]
Closing this.  This is not relevant anymore.
